# **Quantitative Value Strategy**
"Value investing" means investing in the stocks that are cheapest relative to common measures of business value (like earnings or assets).

For this project, we're going to build an investing strategy that selects the 10 stocks with the best value metrics. From there, we will calculate recommended trades for an equal-weight portfolio of these 10 stocks.

## **Library Imports**
The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [ ]:
!pip install numpy
!pip install pandas
!pip install requests
!pip install xlsxwriter
!pip install yfinance

In [7]:
import numpy as np #The Numpy numerical computing library
import pandas as pd #The Pandas data science library
import requests #The requests library for HTTP requests in Python
import xlsxwriter #The XlsxWriter libarary for
import math #The Python math module
from scipy import stats #The SciPy stats module
import yfinance as yf #TO get current rates for nifty 50
from datetime import datetime, timedelta #To foramt date time data

##**Importing Our List of Stocks**

The next thing we need to do is import the constituents of the Nifty 50.

These constituents change over time, so in an ideal world you would connect directly to the index provider (Standard & Poor's) and pull their real-time constituents on a regular basis.

There's a static version of the Nifty 50 constituents available here.[ Click this link](https://drive.google.com/file/d/1S0AsigDz6g9CI0ed2vIERyX7mPXWJ90A/view?usp=sharing) to download them now. Upload this file in the colab so it can be accessed by other files in the script.

Now it's time to import these stocks to our colab file.

In [8]:
stocks = pd.read_csv('/content/nifty50_stocks.csv') #Read CSV file

In [9]:
temp = stocks.iloc[:,0] #dropping all extra columns
df = pd.DataFrame(temp)
df.columns

Index(['Ticker'], dtype='object')

#**Retrieving Data using Yahoo Finance**

To obtain the desired information from Yahoo Finance, we will use the yfinance library, which allows us to fetch data from Yahoo Finance's API. We are interested in retrieving the following details for each stock:




*   Price of each stock.
*   The price-to-earnings ratio.

By utilizing the functionalities provided by yfinance, we can access and extract this data for analysis and further processing.

In [10]:
data =[]

# Loop over the stocks in the index
for symbol in df['Ticker']:

  symbol = symbol + '.NS'
  ticker = yf.Ticker(symbol)
  stock_info = ticker.info
  # Retrieve the data for each stock

  price = stock_info.get('currentPrice') #Current Price
  trailingEps = stock_info.get('trailingEps') #EPS
  pe_ratio = 'N/A'  # Default value if conditions are not met


  if (
        price is not None
        and trailingEps is not None
    ):
        pe_ratio = price / trailingEps

  data.append([symbol, price, pe_ratio, 'N/A'])

In [12]:
# Create a DataFrame from the collected data
columns = ['Ticker', 'Stock Price', 'Price-to-Earnings Ratio', 'Number of Shares to Buy']
df_result = pd.DataFrame(data, columns=columns)

In [13]:
# Print the resulting DataFrame
df_result

           Ticker  Stock Price Price-to-Earnings Ratio Number of Shares to Buy
0   INDUSINDBK.NS      1300.40               13.554305                     N/A
1     AXISBANK.NS       977.40               27.696231                     N/A
2    POWERGRID.NS       244.65               11.448292                     N/A
3     ADANIENT.NS      2507.60               114.39781                     N/A
4           LT.NS      2362.25               31.750672                     N/A
5   ULTRACEMCO.NS      8411.25               47.921889                     N/A
6        CIPLA.NS       988.05               28.515152                     N/A
7       GRASIM.NS      1797.00               17.704433                     N/A
8   TATAMOTORS.NS       572.45               90.865079                     N/A
9    BRITANNIA.NS      4997.70               51.864882                     N/A
10        NTPC.NS       185.95               10.411534                     N/A
11     DRREDDY.NS      4758.95               17.571075                     N/A
12  BAJFINANCE.NS      7098.60               37.097465                     N/A
13    JSWSTEEL.NS       773.20                46.02381                     N/A
14   ICICIBANK.NS       938.75               19.622701                     N/A
15       TITAN.NS      2918.00               79.509537                     N/A
16    HDFCBANK.NS      1601.60               23.067838                     N/A
17        HDFC.NS      2647.80                18.56672                     N/A
18   NESTLEIND.NS     22949.70               87.960216                     N/A
19   COALINDIA.NS       229.30                5.017505                     N/A
20  APOLLOHOSP.NS      5099.50               89.308231                     N/A
21   SUNPHARMA.NS       993.40               28.125708                     N/A
22  BAJAJFINSV.NS      1474.55               36.744331                     N/A
23        BPCL.NS       376.65               37.627373                     N/A
24  BHARTIARTL.NS       831.50               57.069321                     N/A
25      MARUTI.NS      9635.50               35.522581                     N/A
26  ADANIPORTS.NS       743.00                30.24013                     N/A
27  ASIANPAINT.NS      3298.75               77.181797                     N/A
28       WIPRO.NS       395.00               19.091348                     N/A
29   KOTAKBANK.NS      1860.25               24.816569                     N/A
30         M&M.NS      1388.70                     N/A                     N/A
31    RELIANCE.NS      2557.00                     N/A                     N/A
32  TATACONSUM.NS       869.10               66.648773                     N/A
33    HINDALCO.NS       422.15                9.389457                     N/A
34         TCS.NS      3231.15               28.138553                     N/A
35       TECHM.NS      1075.80               19.696082                     N/A
36     SBILIFE.NS      1249.95               77.348391                     N/A
37         ITC.NS       447.40               28.864516                     N/A
38        ONGC.NS       156.95                5.649748                     N/A
39        INFY.NS      1287.40               21.924387                     N/A
40  BAJAJ-AUTO.NS      4751.50                 22.2511                     N/A
41     HCLTECH.NS      1144.60               20.990281                     N/A
42  HINDUNILVR.NS      2709.10               63.281943                     N/A
43         UPL.NS       682.95               14.918087                     N/A
44        SBIN.NS       574.70                9.248471                     N/A
45   TATASTEEL.NS       113.85               16.264286                     N/A
46   EICHERMOT.NS      3590.90               33.962924                     N/A
47    DIVISLAB.NS      3576.60               52.053558                     N/A
48    HDFCLIFE.NS       580.20               90.233281                     N/A
49  HEROMOTOCO.NS      2948.90                21.00057                     N/A

# **Removing Glamour Stocks**
The opposite of a "value stock" is a "glamour stock".

Since the goal of this strategy is to identify the 10 best value stocks from our index, our next step is to remove glamour stocks from the DataFrame.

We'll sort the DataFrame by the stocks' price-to-earnings ratio, and drop all stocks outside the top 10.

In [13]:
df_result['Price-to-Earnings Ratio'] = pd.to_numeric(df_result['Price-to-Earnings Ratio'], errors='coerce')
df_result = df_result.dropna(subset=['Price-to-Earnings Ratio'])
df_result.sort_values('Price-to-Earnings Ratio', inplace = True)
df_result = df_result[df_result['Price-to-Earnings Ratio'] > 0]
df_result = df_result[:10]
df_result.reset_index(inplace = True)
df_result.drop('index', axis=1, inplace = True)
df_result

<ipython-input-13-64d7d990d7b7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result.sort_values('Price-to-Earnings Ratio', inplace = True)

          Ticker  Stock Price  Price-to-Earnings Ratio Number of Shares to Buy
0   COALINDIA.NS       228.60                 5.002188                     N/A
1        ONGC.NS       157.20                 5.658747                     N/A
2        SBIN.NS       567.25                 9.128581                     N/A
3    HINDALCO.NS       423.25                 9.413923                     N/A
4        NTPC.NS       186.55                10.445129                     N/A
5   POWERGRID.NS       245.75                11.499766                     N/A
6  INDUSINDBK.NS      1294.60                13.493850                     N/A
7         UPL.NS       679.40                14.840542                     N/A
8   TATASTEEL.NS       113.75                16.250000                     N/A
9      GRASIM.NS      1768.45                17.423153                     N/A

## **Calculating the Number of Shares to Buy**
We now need to calculate the number of shares we need to buy.

To do this, we will use the portfolio_input function that we created in our momentum project.

I have included this function below.

In [14]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the value of your portfolio:")

    try:
        val = float(portfolio_size)
    except ValueError:
        print("That's not a number! \n Try again:")
        portfolio_size = input("Enter the value of your portfolio:")

Use the `portfolio_input` function to accept a `portfolio_size` variable from the user of this script.

In [15]:
portfolio_input()

Enter the value of your portfolio:200000

ou can now use the global portfolio_size variable to calculate the number of shares that our strategy should purchase.

In [16]:
position_size = float(portfolio_size) / len(df_result.index)
for i in range(0, len(df_result['Ticker'])):
    df_result.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / df_result['Stock Price'][i])
df_result

          Ticker  Stock Price  Price-to-Earnings Ratio Number of Shares to Buy
0   COALINDIA.NS       228.60                 5.002188                      87
1        ONGC.NS       157.20                 5.658747                     127
2        SBIN.NS       567.25                 9.128581                      35
3    HINDALCO.NS       423.25                 9.413923                      47
4        NTPC.NS       186.55                10.445129                     107
5   POWERGRID.NS       245.75                11.499766                      81
6  INDUSINDBK.NS      1294.60                13.493850                      15
7         UPL.NS       679.40                14.840542                      29
8   TATASTEEL.NS       113.75                16.250000                     175
9      GRASIM.NS      1768.45                17.423153                      11

# **Building a Better (and More Realistic) Value Strategy**
Every valuation metric has certain flaws.

For example, the price-to-earnings ratio doesn't work well with stocks with negative earnings.

Similarly, stocks that buyback their own shares are difficult to value using the price-to-book ratio.

Investors typically use a `composite` basket of valuation metrics to build robust quantitative value strategies. In this section, we will filter for stocks with the lowest percentiles on the following metrics:



*   Price-to-earnings ratio
*   Price-to-book ratio


*   Price-to-sales ratio
*   Enterprise Value divided by Earnings Before Interest, Taxes, Depreciation, and Amortization (EV/EBITDA)

*   Enterprise Value divided by Gross Profit (EV/GP)

These metrics aren't provided directly by Yahoo Finance, and must be computed after pulling raw data. We'll start by calculating each data point from scratch.

In [17]:
rv_columns = [
    'Ticker',
    'Price',
    'Number of Shares to Buy',
    'Price-to-Earnings Ratio',
    'PE Percentile',
    'Price-to-Book Ratio',
    'PB Percentile',
    'Price-to-Sales Ratio',
    'PS Percentile',
    'EV/EBITDA',
    'EV/EBITDA Percentile',
    'EV/GP',
    'EV/GP Percentile',
    'RV Score'
]

rv_dataframe = pd.DataFrame(columns = rv_columns)

for symbol in df['Ticker']:

  symbol += '.NS'
  ticker = yf.Ticker(symbol)
  stock_info = ticker.info

  # Retrieve the current price data for each stock
  price = stock_info.get('currentPrice')
  trailingEps = stock_info.get('trailingEps')
  priceToSalesTrailing12Months = stock_info.get('priceToSalesTrailing12Months')
  bookValue = stock_info.get('bookValue')
  totalRevenue = stock_info.get('totalRevenue')
  enterpriseValue = stock_info.get('enterpriseValue')
  enterpriseToEbitda = stock_info.get('enterpriseToEbitda')
  grossMargins = stock_info.get('grossMargins')
  marketCap = stock_info.get('marketCap')
  price_to_earnings_ratio = None
  price_to_book_ratio = None
  price_to_sales_ratio = None
  enterprise_value_to_ebitda = None
  enterprise_value_to_gross_profit = None

  if (
        price is not None
        and trailingEps is not None
        and priceToSalesTrailing12Months is not None
        and bookValue is not None
        and totalRevenue is not None
        and enterpriseValue is not None
        and enterpriseToEbitda is not None
        and grossMargins is not None
    ):
    price_to_earnings_ratio = price / trailingEps
    price_to_book_ratio = price / bookValue
    price_to_sales_ratio = priceToSalesTrailing12Months
    enterprise_value_to_ebitda = enterpriseToEbitda
    enterprise_value_to_gross_profit = enterpriseValue / (grossMargins * totalRevenue)


  # Append the data to the dataframe
  data = pd.DataFrame(
      [
          [
              symbol,
              price,
              'N/A',
              price_to_earnings_ratio,
              'N/A',
              price_to_book_ratio,
              'N/A',
              price_to_sales_ratio,
              'N/A',
              enterprise_value_to_ebitda,
              'N/A',
              enterprise_value_to_gross_profit,
              'N/A',
              'N/A',
          ]
      ],
      columns=rv_columns,
  )
  rv_dataframe = pd.concat([rv_dataframe, data], ignore_index=True)

In [18]:
rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,INDUSINDBK.NS,1294.05,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,N/A
1,AXISBANK.NS,974.20,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,N/A
2,POWERGRID.NS,245.65,N/A,11.495087,N/A,2.065379,N/A,3.759261,N/A,7.47,N/A,6.469557,N/A,N/A
3,ADANIENT.NS,2484.65,N/A,113.350821,N/A,8.566754,N/A,2.087717,N/A,36.28,N/A,9.760968,N/A,N/A
4,LT.NS,2356.25,N/A,31.670027,N/A,3.706865,N/A,1.777884,N/A,17.217,N/A,5.853944,N/A,N/A
5,ULTRACEMCO.NS,8318.05,N/A,47.390896,N/A,4.414789,N/A,3.792093,N/A,23.081,N/A,6.996667,N/A,N/A
6,CIPLA.NS,995.15,N/A,28.720058,N/A,3.431493,N/A,3.530544,N/A,15.009,N/A,5.203176,N/A,N/A
7,GRASIM.NS,1768.00,N/A,17.418719,N/A,1.474171,N/A,0.98966,N/A,11.372,N/A,3.698718,N/A,N/A
8,TATAMOTORS.NS,568.20,N/A,90.190476,N/A,4.801501,N/A,0.591438,N/A,14.258,N/A,2.237546,N/A,N/A
9,BRITANNIA.NS,4959.15,N/A,51.464819,N/A,33.80286,N/A,7.327977,N/A,42.416,N/A,17.896892,N/A,N/A
10,NTPC.NS,186.60,N/A,10.447928,N/A,1.231358,N/A,1.02686,N/A,8.426,N/A,5.726952,N/A,N/A
11,DRREDDY.NS,4805.10,N/A,17.741471,N/A,3.455731,N/A,3.246446,N/A,11.124,N/A,5.255352,N/A,N/A
12,BAJFINANCE.NS,7095.55,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
13,JSWSTEEL.NS,769.25,N/A,45.78869,N/A,2.815177,N/A,1.116942,N/A,13.334,N/A,5.182691,N/A,N/A
14,ICICIBANK.NS,927.00,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
15,TITAN.NS,2903.95,N/A,79.126703,N/A,21.761237,N/A,6.353879,N/A,54.126,N/A,25.839615,N/A,N/A
16,HDFCBANK.NS,1582.70,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
17,HDFC.NS,2622.75,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
18,NESTLEIND.NS,22944.00,N/A,87.93837,N/A,89.955657,N/A,12.503132,N/A,57.49,N/A,23.265259,N/A,N/A
19,COALINDIA.NS,228.50,N/A,5.0,N/A,2.459528,N/A,1.103355,N/A,2.761,N/A,1.182073,N/A,N/A
20,APOLLOHOSP.NS,5239.00,N/A,91.751313,N/A,12.156778,N/A,4.534488,N/A,36.899,N/A,12.830488,N/A,N/A
21,SUNPHARMA.NS,988.20,N/A,27.978482,N/A,4.219489,N/A,5.402714,N/A,19.619,N/A,6.952151,N/A,N/A
22,BAJAJFINSV.NS,1475.00,N/A,36.755544,N/A,5.065212,N/A,2.914985,N/A,14.461,N/A,9.991395,N/A,N/A
23,BPCL.NS,378.35,N/A,37.797203,N/A,1.505499,N/A,0.173448,N/A,13.049,N/A,3.554238,N/A,N/A
24,BHARTIARTL.NS,828.30,N/A,56.849691,N/A,6.369383,N/A,3.41963,N/A,10.118,N/A,8.365445,N/A,N/A
25,MARUTI.NS,9592.05,N/A,35.362396,N/A,4.689473,N/A,2.473053,N/A,26.247,N/A,9.192747,N/A,N/A
26,ADANIPORTS.NS,739.25,N/A,30.087505,N/A,3.506363,N/A,7.703874,N/A,16.066,N/A,14.706824,N/A,N/A
27,ASIANPAINT.NS,3289.25,N/A,76.959523,N/A,19.728595,N/A,9.16073,N/A,52.28,N/A,23.754865,N/A,N/A
28,WIPRO.NS,389.25,N/A,18.813436,N/A,2.729663,N/A,2.357767,N/A,12.006,N/A,7.503269,N/A,N/A
29,KOTAKBANK.NS,1830.25,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
30,M&M.NS,1389.35,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
31,RELIANCE.NS,2547.05,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
32,TATACONSUM.NS,862.40,N/A,66.134969,N/A,4.922234,N/A,5.812745,N/A,44.846,N/A,13.96198,N/A,N/A
33,HINDALCO.NS,423.00,N/A,9.408363,N/A,0.991452,N/A,0.422784,N/A,6.084,N/A,2.13852,N/A,N/A
34,TCS.NS,3218.85,N/A,28.031438,N/A,13.025242,N/A,5.224004,N/A,20.0,N/A,11.998651,N/A,N/A
35,TECHM.NS,1080.40,N/A,19.7803,N/A,3.41309,N/A,1.975537,N/A,11.363,N/A,5.184352,N/A,N/A
36,SBILIFE.NS,1240.25,N/A,76.748144,N/A,9.538037,N/A,1.539675,N/A,61.256,N/A,19.250489,N/A,N/A
37,ITC.NS,446.75,N/A,28.822581,N/A,8.017767,N/A,7.826974,N/A,20.661,N/A,12.645973,N/A,N/A
38,ONGC.NS,157.30,N/A,5.662347,N/A,0.705929,N/A,0.28896,N/A,4.011,N/A,1.434464,N/A,N/A
39,INFY.NS,1287.15,N/A,21.920129,N/A,580.581867,N/A,292.4358,N/A,1279.491,N/A,998.286838,N/A,N/A
40,BAJAJ-AUTO.NS,4715.45,N/A,22.08228,N/A,4.540308,N/A,3.555443,N/A,16.818,N/A,11.15182,N/A,N/A
41,HCLTECH.NS,1144.25,N/A,20.983862,N/A,389.068344,N/A,247.95387,N/A,1158.859,N/A,671.313485,N/A,N/A
42,HINDUNILVR.NS,2683.20,N/A,62.676945,N/A,12.532637,N/A,10.406769,N/A,45.916,N/A,21.935955,N/A,N/A
43,UPL.NS,679.75,N/A,14.848187,N/A,1.87685,N/A,0.95234,N/A,6.632,N/A,2.814703,N/A,N/A
44,SBIN.NS,567.25,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
45,TATASTEEL.NS,113.80,N/A,16.257143,N/A,1.34922,N/A,0.571519,N/A,7.099,N/A,1.702001,N/A,N/A
46,EICHERMOT.NS,3535.80,N/A,33.441786,N/A,6.451272,N/A,6.825569,N/A,30.501,N/A,16.249197,N/A,N/A
47,DIVISLAB.NS,3577.40,N/A,52.065202,N/A,7.438984,N/A,12.226424,N/A,37.307,N/A,18.740015,N/A,N/A
48,HDFCLIFE.NS,577.00,N/A,89.735614,N/A,9.455451,N/A,1.752871,N/A,84.606,N/A,11.931096,N/A,N/A
49,HEROMOTOCO.NS,2839.10,N/A,20.21863,N/A,3.406312,N/A,1.661002,N/A,13.479,N/A,5.402234,N/A,N/A

## **Dealing With Missing Data in Our DataFrame**
Our DataFrame contains some missing data because all of the metrics we require are not available through yf that we're using.

You can use pandas' isnull method to identify missing data:

In [19]:
rv_dataframe[rv_dataframe.isnull().any(axis=1)]

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,INDUSINDBK.NS,1294.05,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,N/A
1,AXISBANK.NS,974.20,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,NaN,N/A,N/A
12,BAJFINANCE.NS,7095.55,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
14,ICICIBANK.NS,927.00,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
16,HDFCBANK.NS,1582.70,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
17,HDFC.NS,2622.75,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
29,KOTAKBANK.NS,1830.25,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
30,M&M.NS,1389.35,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
31,RELIANCE.NS,2547.05,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A
44,SBIN.NS,567.25,N/A,None,N/A,None,N/A,None,N/A,None,N/A,None,N/A,N/A

Dealing with missing data is an important topic in data science.

There are two main approaches:


*   Drop missing data from the data set (pandas' dropna method is useful here)

*   Replace missing data with a new value (pandas' fillna method is useful here)




In this tutorial, we will replace missing data with the average non-NaN data point from that column.

Here is the code to do this:

In [20]:
for column in ['Price-to-Earnings Ratio', 'Price-to-Book Ratio','Price-to-Sales Ratio',  'EV/EBITDA','EV/GP']:
    rv_dataframe[column].fillna(rv_dataframe[column].mean(), inplace = True)

Now, if we run the statement from earlier to print rows that contain missing data, nothing should be returned:

In [21]:
rv_dataframe[rv_dataframe.isnull().any(axis=1)]

Empty DataFrame
Columns: [Ticker, Price, Number of Shares to Buy, Price-to-Earnings Ratio, PE Percentile, Price-to-Book Ratio, PB Percentile, Price-to-Sales Ratio, PS Percentile, EV/EBITDA, EV/EBITDA Percentile, EV/GP, EV/GP Percentile, RV Score]
Index: []

# **Calculating Value Percentiles**
We now need to calculate value score percentiles for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

*   Price-to-earnings ratio
*   Price-to-book ratio


*   Price-to-sales ratio
*   EV/EBITDA


*   EV/GP


Here's how we'll do this:

In [22]:
metrics = {
            'Price-to-Earnings Ratio': 'PE Percentile',
            'Price-to-Book Ratio':'PB Percentile',
            'Price-to-Sales Ratio': 'PS Percentile',
            'EV/EBITDA':'EV/EBITDA Percentile',
            'EV/GP':'EV/GP Percentile'
}

for row in rv_dataframe.index:
    for metric in metrics.keys():
        metric_scores = pd.to_numeric(rv_dataframe[metric], errors='coerce').to_numpy()  # Convert the metric values to a NumPy array
        row_metric_score = pd.to_numeric(rv_dataframe.loc[row, metric], errors='coerce')  # Convert to numeric

        # Calculate percentile manually
        non_nan_scores = metric_scores[~np.isnan(metric_scores)]
        count = np.sum(non_nan_scores <= row_metric_score)
        total = len(non_nan_scores)
        percentile = count / total

        rv_dataframe.loc[row, metrics[metric]] = percentile
# Print each percentile score to make sure it was calculated properly
# for metric in metrics.values():
#     print(rv_dataframe[metric])

#Print the entire DataFrame
rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,INDUSINDBK.NS,1294.05,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
1,AXISBANK.NS,974.20,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
2,POWERGRID.NS,245.65,N/A,11.495087,0.1,2.065379,0.16,3.759261,0.48,7.47000,0.12,6.469557,0.32,N/A
3,ADANIENT.NS,2484.65,N/A,113.350821,1.0,8.566754,0.58,2.087717,0.32,36.28000,0.56,9.760968,0.44,N/A
4,LT.NS,2356.25,N/A,31.670027,0.42,3.706865,0.34,1.777884,0.28,17.21700,0.42,5.853944,0.3,N/A
5,ULTRACEMCO.NS,8318.05,N/A,47.390896,0.74,4.414789,0.38,3.792093,0.5,23.08100,0.5,6.996667,0.36,N/A
6,CIPLA.NS,995.15,N/A,28.720058,0.36,3.431493,0.28,3.530544,0.44,15.00900,0.36,5.203176,0.22,N/A
7,GRASIM.NS,1768.00,N/A,17.418719,0.16,1.474171,0.1,0.989660,0.14,11.37200,0.22,3.698718,0.16,N/A
8,TATAMOTORS.NS,568.20,N/A,90.190476,0.96,4.801501,0.44,0.591438,0.1,14.25800,0.32,2.237546,0.1,N/A
9,BRITANNIA.NS,4959.15,N/A,51.464819,0.76,33.802860,0.94,7.327977,0.64,42.41600,0.62,17.896892,0.64,N/A
10,NTPC.NS,186.60,N/A,10.447928,0.08,1.231358,0.06,1.026860,0.16,8.42600,0.14,5.726952,0.28,N/A
11,DRREDDY.NS,4805.10,N/A,17.741471,0.18,3.455731,0.3,3.246446,0.4,11.12400,0.18,5.255352,0.24,N/A
12,BAJFINANCE.NS,7095.55,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
13,JSWSTEEL.NS,769.25,N/A,45.788690,0.72,2.815177,0.22,1.116942,0.2,13.33400,0.28,5.182691,0.18,N/A
14,ICICIBANK.NS,927.00,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
15,TITAN.NS,2903.95,N/A,79.126703,0.9,21.761237,0.72,6.353879,0.6,54.12600,0.7,25.839615,0.76,N/A
16,HDFCBANK.NS,1582.70,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
17,HDFC.NS,2622.75,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
18,NESTLEIND.NS,22944.00,N/A,87.938370,0.92,89.955657,0.96,12.503132,0.76,57.49000,0.72,23.265259,0.72,N/A
19,COALINDIA.NS,228.50,N/A,5.000000,0.02,2.459528,0.18,1.103355,0.18,2.76100,0.02,1.182073,0.02,N/A
20,APOLLOHOSP.NS,5239.00,N/A,91.751313,0.98,12.156778,0.64,4.534488,0.52,36.89900,0.58,12.830488,0.56,N/A
21,SUNPHARMA.NS,988.20,N/A,27.978482,0.32,4.219489,0.36,5.402714,0.56,19.61900,0.44,6.952151,0.34,N/A
22,BAJAJFINSV.NS,1475.00,N/A,36.755544,0.48,5.065212,0.48,2.914985,0.38,14.46100,0.34,9.991395,0.46,N/A
23,BPCL.NS,378.35,N/A,37.797203,0.5,1.505499,0.12,0.173448,0.02,13.04900,0.26,3.554238,0.14,N/A
24,BHARTIARTL.NS,828.30,N/A,56.849691,0.8,6.369383,0.5,3.419630,0.42,10.11800,0.16,8.365445,0.4,N/A
25,MARUTI.NS,9592.05,N/A,35.362396,0.46,4.689473,0.42,2.473053,0.36,26.24700,0.52,9.192747,0.42,N/A
26,ADANIPORTS.NS,739.25,N/A,30.087505,0.4,3.506363,0.32,7.703874,0.66,16.06600,0.38,14.706824,0.6,N/A
27,ASIANPAINT.NS,3289.25,N/A,76.959523,0.88,19.728595,0.7,9.160730,0.7,52.28000,0.68,23.754865,0.74,N/A
28,WIPRO.NS,389.25,N/A,18.813436,0.2,2.729663,0.2,2.357767,0.34,12.00600,0.24,7.503269,0.38,N/A
29,KOTAKBANK.NS,1830.25,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
30,M&M.NS,1389.35,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
31,RELIANCE.NS,2547.05,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
32,TATACONSUM.NS,862.40,N/A,66.134969,0.84,4.922234,0.46,5.812745,0.58,44.84600,0.64,13.961980,0.58,N/A
33,HINDALCO.NS,423.00,N/A,9.408363,0.06,0.991452,0.04,0.422784,0.06,6.08400,0.06,2.138520,0.08,N/A
34,TCS.NS,3218.85,N/A,28.031438,0.34,13.025242,0.68,5.224004,0.54,20.00000,0.46,11.998651,0.52,N/A
35,TECHM.NS,1080.40,N/A,19.780300,0.22,3.413090,0.26,1.975537,0.3,11.36300,0.2,5.184352,0.2,N/A
36,SBILIFE.NS,1240.25,N/A,76.748144,0.86,9.538037,0.62,1.539675,0.22,61.25600,0.74,19.250489,0.68,N/A
37,ITC.NS,446.75,N/A,28.822581,0.38,8.017767,0.56,7.826974,0.68,20.66100,0.48,12.645973,0.54,N/A
38,ONGC.NS,157.30,N/A,5.662347,0.04,0.705929,0.02,0.288960,0.04,4.01100,0.04,1.434464,0.04,N/A
39,INFY.NS,1287.15,N/A,21.920129,0.28,580.581867,1.0,292.435800,1.0,1279.49100,1.0,998.286838,1.0,N/A
40,BAJAJ-AUTO.NS,4715.45,N/A,22.082280,0.3,4.540308,0.4,3.555443,0.46,16.81800,0.4,11.151820,0.48,N/A
41,HCLTECH.NS,1144.25,N/A,20.983862,0.26,389.068344,0.98,247.953870,0.98,1158.85900,0.98,671.313485,0.98,N/A
42,HINDUNILVR.NS,2683.20,N/A,62.676945,0.82,12.532637,0.66,10.406769,0.72,45.91600,0.66,21.935955,0.7,N/A
43,UPL.NS,679.75,N/A,14.848187,0.12,1.876850,0.14,0.952340,0.12,6.63200,0.08,2.814703,0.12,N/A
44,SBIN.NS,567.25,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,N/A
45,TATASTEEL.NS,113.80,N/A,16.257143,0.14,1.349220,0.08,0.571519,0.08,7.09900,0.1,1.702001,0.06,N/A
46,EICHERMOT.NS,3535.80,N/A,33.441786,0.44,6.451272,0.52,6.825569,0.62,30.50100,0.54,16.249197,0.62,N/A
47,DIVISLAB.NS,3577.40,N/A,52.065202,0.78,7.438984,0.54,12.226424,0.74,37.30700,0.6,18.740015,0.66,N/A
48,HDFCLIFE.NS,577.00,N/A,89.735614,0.94,9.455451,0.6,1.752871,0.26,84.60600,0.96,11.931096,0.5,N/A
49,HEROMOTOCO.NS,2839.10,N/A,20.218630,0.24,3.406312,0.24,1.661002,0.24,13.47900,0.3,5.402234,0.26,N/A

## **Calculating the RV Score**
We'll now calculate our RV Score (which stands for Robust Value), which is the value score that we'll use to filter for stocks in this investing strategy.

The RV Score will be the arithmetic mean of the 4 percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the mean function from Python's built-in statistics module.

In [23]:
from statistics import mean

for row in rv_dataframe.index:
    value_percentiles = []
    for metric in metrics.keys():
        value_percentiles.append(rv_dataframe.loc[row, metrics[metric]])
    rv_dataframe.loc[row, 'RV Score'] = mean(value_percentiles)

rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,INDUSINDBK.NS,1294.05,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
1,AXISBANK.NS,974.20,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
2,POWERGRID.NS,245.65,N/A,11.495087,0.1,2.065379,0.16,3.759261,0.48,7.47000,0.12,6.469557,0.32,0.236
3,ADANIENT.NS,2484.65,N/A,113.350821,1.0,8.566754,0.58,2.087717,0.32,36.28000,0.56,9.760968,0.44,0.58
4,LT.NS,2356.25,N/A,31.670027,0.42,3.706865,0.34,1.777884,0.28,17.21700,0.42,5.853944,0.3,0.352
5,ULTRACEMCO.NS,8318.05,N/A,47.390896,0.74,4.414789,0.38,3.792093,0.5,23.08100,0.5,6.996667,0.36,0.496
6,CIPLA.NS,995.15,N/A,28.720058,0.36,3.431493,0.28,3.530544,0.44,15.00900,0.36,5.203176,0.22,0.332
7,GRASIM.NS,1768.00,N/A,17.418719,0.16,1.474171,0.1,0.989660,0.14,11.37200,0.22,3.698718,0.16,0.156
8,TATAMOTORS.NS,568.20,N/A,90.190476,0.96,4.801501,0.44,0.591438,0.1,14.25800,0.32,2.237546,0.1,0.384
9,BRITANNIA.NS,4959.15,N/A,51.464819,0.76,33.802860,0.94,7.327977,0.64,42.41600,0.62,17.896892,0.64,0.72
10,NTPC.NS,186.60,N/A,10.447928,0.08,1.231358,0.06,1.026860,0.16,8.42600,0.14,5.726952,0.28,0.144
11,DRREDDY.NS,4805.10,N/A,17.741471,0.18,3.455731,0.3,3.246446,0.4,11.12400,0.18,5.255352,0.24,0.26
12,BAJFINANCE.NS,7095.55,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
13,JSWSTEEL.NS,769.25,N/A,45.788690,0.72,2.815177,0.22,1.116942,0.2,13.33400,0.28,5.182691,0.18,0.32
14,ICICIBANK.NS,927.00,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
15,TITAN.NS,2903.95,N/A,79.126703,0.9,21.761237,0.72,6.353879,0.6,54.12600,0.7,25.839615,0.76,0.736
16,HDFCBANK.NS,1582.70,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
17,HDFC.NS,2622.75,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
18,NESTLEIND.NS,22944.00,N/A,87.938370,0.92,89.955657,0.96,12.503132,0.76,57.49000,0.72,23.265259,0.72,0.816
19,COALINDIA.NS,228.50,N/A,5.000000,0.02,2.459528,0.18,1.103355,0.18,2.76100,0.02,1.182073,0.02,0.084
20,APOLLOHOSP.NS,5239.00,N/A,91.751313,0.98,12.156778,0.64,4.534488,0.52,36.89900,0.58,12.830488,0.56,0.656
21,SUNPHARMA.NS,988.20,N/A,27.978482,0.32,4.219489,0.36,5.402714,0.56,19.61900,0.44,6.952151,0.34,0.404
22,BAJAJFINSV.NS,1475.00,N/A,36.755544,0.48,5.065212,0.48,2.914985,0.38,14.46100,0.34,9.991395,0.46,0.428
23,BPCL.NS,378.35,N/A,37.797203,0.5,1.505499,0.12,0.173448,0.02,13.04900,0.26,3.554238,0.14,0.208
24,BHARTIARTL.NS,828.30,N/A,56.849691,0.8,6.369383,0.5,3.419630,0.42,10.11800,0.16,8.365445,0.4,0.456
25,MARUTI.NS,9592.05,N/A,35.362396,0.46,4.689473,0.42,2.473053,0.36,26.24700,0.52,9.192747,0.42,0.436
26,ADANIPORTS.NS,739.25,N/A,30.087505,0.4,3.506363,0.32,7.703874,0.66,16.06600,0.38,14.706824,0.6,0.472
27,ASIANPAINT.NS,3289.25,N/A,76.959523,0.88,19.728595,0.7,9.160730,0.7,52.28000,0.68,23.754865,0.74,0.74
28,WIPRO.NS,389.25,N/A,18.813436,0.2,2.729663,0.2,2.357767,0.34,12.00600,0.24,7.503269,0.38,0.272
29,KOTAKBANK.NS,1830.25,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
30,M&M.NS,1389.35,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
31,RELIANCE.NS,2547.05,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
32,TATACONSUM.NS,862.40,N/A,66.134969,0.84,4.922234,0.46,5.812745,0.58,44.84600,0.64,13.961980,0.58,0.62
33,HINDALCO.NS,423.00,N/A,9.408363,0.06,0.991452,0.04,0.422784,0.06,6.08400,0.06,2.138520,0.08,0.06
34,TCS.NS,3218.85,N/A,28.031438,0.34,13.025242,0.68,5.224004,0.54,20.00000,0.46,11.998651,0.52,0.508
35,TECHM.NS,1080.40,N/A,19.780300,0.22,3.413090,0.26,1.975537,0.3,11.36300,0.2,5.184352,0.2,0.236
36,SBILIFE.NS,1240.25,N/A,76.748144,0.86,9.538037,0.62,1.539675,0.22,61.25600,0.74,19.250489,0.68,0.624
37,ITC.NS,446.75,N/A,28.822581,0.38,8.017767,0.56,7.826974,0.68,20.66100,0.48,12.645973,0.54,0.528
38,ONGC.NS,157.30,N/A,5.662347,0.04,0.705929,0.02,0.288960,0.04,4.01100,0.04,1.434464,0.04,0.036
39,INFY.NS,1287.15,N/A,21.920129,0.28,580.581867,1.0,292.435800,1.0,1279.49100,1.0,998.286838,1.0,0.856
40,BAJAJ-AUTO.NS,4715.45,N/A,22.082280,0.3,4.540308,0.4,3.555443,0.46,16.81800,0.4,11.151820,0.48,0.408
41,HCLTECH.NS,1144.25,N/A,20.983862,0.26,389.068344,0.98,247.953870,0.98,1158.85900,0.98,671.313485,0.98,0.836
42,HINDUNILVR.NS,2683.20,N/A,62.676945,0.82,12.532637,0.66,10.406769,0.72,45.91600,0.66,21.935955,0.7,0.712
43,UPL.NS,679.75,N/A,14.848187,0.12,1.876850,0.14,0.952340,0.12,6.63200,0.08,2.814703,0.12,0.116
44,SBIN.NS,567.25,N/A,40.972927,0.7,32.530699,0.92,17.219504,0.96,84.10095,0.94,51.189065,0.96,0.896
45,TATASTEEL.NS,113.80,N/A,16.257143,0.14,1.349220,0.08,0.571519,0.08,7.09900,0.1,1.702001,0.06,0.092
46,EICHERMOT.NS,3535.80,N/A,33.441786,0.44,6.451272,0.52,6.825569,0.62,30.50100,0.54,16.249197,0.62,0.548
47,DIVISLAB.NS,3577.40,N/A,52.065202,0.78,7.438984,0.54,12.226424,0.74,37.30700,0.6,18.740015,0.66,0.664
48,HDFCLIFE.NS,577.00,N/A,89.735614,0.94,9.455451,0.6,1.752871,0.26,84.60600,0.96,11.931096,0.5,0.652
49,HEROMOTOCO.NS,2839.10,N/A,20.218630,0.24,3.406312,0.24,1.661002,0.24,13.47900,0.3,5.402234,0.26,0.256

## **Selecting the 10 Best Value Stocks**
As before, we can identify the 10 best value stocks in our index by sorting the DataFrame on the RV Score column and dropping all but the top 10 entries.

In [24]:
rv_dataframe.sort_values('RV Score', inplace = True)
rv_dataframe = rv_dataframe[:10]
rv_dataframe.reset_index(inplace = True)
rv_dataframe.drop('index', axis=1, inplace = True)
rv_dataframe

<ipython-input-24-9502b97457f8>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rv_dataframe.drop('index', axis=1, inplace = True)

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,ONGC.NS,157.30,N/A,5.662347,0.04,0.705929,0.02,0.288960,0.04,4.011,0.04,1.434464,0.04,0.036
1,HINDALCO.NS,423.00,N/A,9.408363,0.06,0.991452,0.04,0.422784,0.06,6.084,0.06,2.138520,0.08,0.06
2,COALINDIA.NS,228.50,N/A,5.000000,0.02,2.459528,0.18,1.103355,0.18,2.761,0.02,1.182073,0.02,0.084
3,TATASTEEL.NS,113.80,N/A,16.257143,0.14,1.349220,0.08,0.571519,0.08,7.099,0.1,1.702001,0.06,0.092
4,UPL.NS,679.75,N/A,14.848187,0.12,1.876850,0.14,0.952340,0.12,6.632,0.08,2.814703,0.12,0.116
5,NTPC.NS,186.60,N/A,10.447928,0.08,1.231358,0.06,1.026860,0.16,8.426,0.14,5.726952,0.28,0.144
6,GRASIM.NS,1768.00,N/A,17.418719,0.16,1.474171,0.1,0.989660,0.14,11.372,0.22,3.698718,0.16,0.156
7,BPCL.NS,378.35,N/A,37.797203,0.5,1.505499,0.12,0.173448,0.02,13.049,0.26,3.554238,0.14,0.208
8,POWERGRID.NS,245.65,N/A,11.495087,0.1,2.065379,0.16,3.759261,0.48,7.470,0.12,6.469557,0.32,0.236
9,TECHM.NS,1080.40,N/A,19.780300,0.22,3.413090,0.26,1.975537,0.3,11.363,0.2,5.184352,0.2,0.236

# **Calculating the Number of Shares to Buy**
We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a for loop to calculate the number of shares to buy for each stock in our investment universe.

In [25]:
portfolio_input()

Enter the value of your portfolio:200000

In [26]:
position_size = float(portfolio_size) / len(rv_dataframe.index)
for i in range(0, len(rv_dataframe['Ticker'])):
    rv_dataframe.loc[i, 'Number of Shares to Buy'] = math.floor(position_size / rv_dataframe['Price'][i])
rv_dataframe

,Ticker,Price,Number of Shares to Buy,Price-to-Earnings Ratio,PE Percentile,Price-to-Book Ratio,PB Percentile,Price-to-Sales Ratio,PS Percentile,EV/EBITDA,EV/EBITDA Percentile,EV/GP,EV/GP Percentile,RV Score
0,ONGC.NS,157.30,127,5.662347,0.04,0.705929,0.02,0.288960,0.04,4.011,0.04,1.434464,0.04,0.036
1,HINDALCO.NS,423.00,47,9.408363,0.06,0.991452,0.04,0.422784,0.06,6.084,0.06,2.138520,0.08,0.06
2,COALINDIA.NS,228.50,87,5.000000,0.02,2.459528,0.18,1.103355,0.18,2.761,0.02,1.182073,0.02,0.084
3,TATASTEEL.NS,113.80,175,16.257143,0.14,1.349220,0.08,0.571519,0.08,7.099,0.1,1.702001,0.06,0.092
4,UPL.NS,679.75,29,14.848187,0.12,1.876850,0.14,0.952340,0.12,6.632,0.08,2.814703,0.12,0.116
5,NTPC.NS,186.60,107,10.447928,0.08,1.231358,0.06,1.026860,0.16,8.426,0.14,5.726952,0.28,0.144
6,GRASIM.NS,1768.00,11,17.418719,0.16,1.474171,0.1,0.989660,0.14,11.372,0.22,3.698718,0.16,0.156
7,BPCL.NS,378.35,52,37.797203,0.5,1.505499,0.12,0.173448,0.02,13.049,0.26,3.554238,0.14,0.208
8,POWERGRID.NS,245.65,81,11.495087,0.1,2.065379,0.16,3.759261,0.48,7.470,0.12,6.469557,0.32,0.236
9,TECHM.NS,1080.40,18,19.780300,0.22,3.413090,0.26,1.975537,0.3,11.363,0.2,5.184352,0.2,0.236

## **Formatting Our Excel Output**
We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization.

In [65]:
writer = pd.ExcelWriter('value_strategy.xlsx', engine='xlsxwriter')
rv_dataframe.to_excel(writer, sheet_name='Value Strategy', index = False)

## **Creating the Formats We'll Need For Our .xlsx File**
We'll need four main formats for our Excel document:



*   String format for tickers
*   $XX.XX format for stock prices

*   $XX,XXX format for market capitalization
*   Integer format for the number of shares to purchase


*   Float formats with 3 decimal for each valuation metric


Run this code cell before proceeding.

In [66]:
string_template = writer.book.add_format(
        {
            'font_color': '#ffffff',
            'bg_color': '#0a0a23',
            'border': 1
        }
    )

INR_template = writer.book.add_format(
        {
            'num_format':'₹0.00',
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'border': 1
        }
    )
float_template = writer.book.add_format(
        {
            'num_format':'0.000',
            'border': 1
        }
    )
percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'border': 1
        }
    )

In [71]:
column_formats = {
                    'A': ['Ticker', string_template],
                    'B': ['Price', INR_template],
                    'C': ['Number of Shares to Buy', integer_template],
                    'D': ['Price-to-Earnings Ratio', float_template],
                    'E': ['PE Percentile', percent_template],
                    'F': ['Price-to-Book Ratio', float_template],
                    'G': ['PB Percentile',percent_template],
                    'H': ['Price-to-Sales Ratio', float_template],
                    'I': ['PS Percentile', percent_template],
                    'J': ['EV/EBITDA', float_template],
                    'K': ['EV/EBITDA Percentile', percent_template],
                    'L': ['EV/GP', float_template],
                    'M': ['EV/GP Percentile', percent_template],
                    'N': ['RV Score', percent_template]
                 }

for column in column_formats.keys():
  writer.sheets['Value Strategy'].set_column(f'{column}:{column}', 20, column_formats[column][1])
  writer.sheets['Value Strategy'].write(f'{column}1', column_formats[column][0], string_template)

## **Saving Our Excel Output**
Saving our Excel output is very easy:

In [70]:
writer.save()

<ipython-input-70-16d93d5523a4>:1: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()
/usr/local/lib/python3.10/dist-packages/xlsxwriter/workbook.py:339: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")